.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "F5C" "1" "August 2021" "" ""
.
.SH "NAME"
\fBf5c\fR \- Ultra\-fast methylation calling and event alignment tool for nanopore sequencing data with optional CUDA acceleration
.
.SH "SYNOPSIS"
.
.TP
indexing
\fBf5c index \-d [fast5_folder] [read\.fastq|fasta] f5c index \-\-slow5 [slow5_file] [read\.fastq|fasta]\fR
.
.TP
methylation calling
\fBf5c call\-methylation \-b [reads\.sorted\.bam] \-g [ref\.fa] \-r [reads\.fastq|fasta] > [meth\.tsv] #specify \-\-slow5 [slow5_file] to use a slow5 file instead of fast5\. f5c meth\-freq \-i [meth\.tsv] > [freq\.tsv]\fR
.
.TP
event alignment
\fBf5c eventalign \-b [reads\.sorted\.bam] \-g [ref\.fa] \-r [reads\.fastq|fasta] > [events\.tsv] #specify \-\-rna for direct RNA data\. specify \-\-slow5 [slow5_file] to use a slow5 file instead of fast5\.\fR
.
.SH "DESCRIPTION"
Given a set of base\-called nanopore reads and associated raw signals, f5c call\-methylation detects the methylated cytosine at genomic CpG cites and f5c eventalign aligns raw nanopore signals (events) to the reference k\-mers\. f5c can optionally utilise CUDA enabled NVIDIA graphics cards for acceleration\. f5c is a heavily re\-engineered and optimised implementation of the call\-methylation and eventalign modules in Nanopolish\.
.
.SH "COMMANDS"
.
.TP
\fBindex\fR:
.
.br
Build an index for accessing the base sequence and raw signal for a given read ID (optimised nanopolish index)\.

.
.TP
\fBcall\-methylation\fR:
.
.br
Classify nucleotides as methylated or not at genomic CpG sites (optimised nanopolish call\-methylation)\.

.
.TP
\fBmeth\-freq\fR:
.
.br
Calculate methylation frequency at genomic CpG sites (optimised nanopolish calculate_methylation_frequency\.py)\.

.
.TP
\fBfreq\-merge\fR:
.
.br
Merge multiple methylation frequency tsv files\.

.
.TP
\fBeventalign\fR:
.
.br
Align nanopore events to reference k\-mers (optimised nanopolish eventalign)\.

.
.SH "OPTIONS"
.
.SS "index"
.
.nf

f5c index [OPTIONS] \-d nanopore_raw_file_directory reads\.fastq
f5c index [OPTIONS] \-\-slow5 signals\.blow5 reads\.fastq
.
.fi
.
.P
Build an index for accessing the base sequence and raw signal for a given read IDs\. f5c index is an extended and optimised version of nanopolish index by Jared Simpson\. The output of f5c index (for fast5) is equivalent to that from nanopolish index\.
.
.IP "\(bu" 4
\fB\-h\fR, \fB\-\-help\fR:
.
.br
Print the help to the standard out\.
.
.IP "\(bu" 4
\fB\-d\fR, \fB\-\-directory\fR:
.
.br
Path to the directory containing fast5 files\. This option can be given multiple times\. Both multi\-fast5 and single\-fast5 are supported\. The specified directory will be recursively searched for files ending with the \.fast5 extension\.
.
.IP "\(bu" 4
\fB\-s\fR, \fB\-\-sequencing\-summary\fR:
.
.br
The sequencing summary file generated by Guppy base\-caller\. This option is not encouraged as inconsistencies in the format of sequencing summary files lead to issues during subsequent steps\.
.
.IP "\(bu" 4
\fB\-f\fR, \fB\-\-summary\-fofn\fR:
.
.br
File containing the paths to the sequencing summary files (one per line)\. This option is not encouraged as inconsistencies in the format of sequencing summary files lead to issues during subsequent steps\.
.
.IP "\(bu" 4
\fB\-t INT\fR:
.
.br
Number of threads used for bgzf compression [default value: 1]\. Increasing the number of threads makes indexing faster\. Ideally, this should be the number of CPU cores\.
.
.IP "\(bu" 4
\fB\-\-iop INT\fR:
.
.br
Number of I/O processes to read fast5 files [default value: 1]\. Increasing the number of I/O processes makes indexing significantly faster, especially on HPC with RAID systems (multiple disks) where this can be as high as 64\. Note that unless value of iop is 1, options \-s and \-f are ignored\.
.
.IP "\(bu" 4
\fB\-\-slow5 FILE\fR:
.
.br
slow5 file containing raw signals\. \-d, \-s, \-f and \-\-iop options are not required when indexing using a slow5 file\.
.
.IP "\(bu" 4
\fB\-\-verbose INT\fR:
.
.br
Verbosity level for the log messages [default value: 0]\.
.
.IP "\(bu" 4
\fB\-\-version\fR:
.
.br
Print the version number to the standard out\.
.
.IP "" 0
.
.SS "call\-methylation"
.
.nf

f5c call\-methylation [OPTIONS] \-r reads\.fa \-b alignments\.bam \-g genome\.fa
f5c call\-methylation [OPTIONS] \-r reads\.fa \-b alignments\.bam \-g genome\.fa \-\-slow5 signals\.blow5
.
.fi
.
.P
Classify nucleotides as methylated or not at genomic CpG cites (optimised nanopolish call\-methylation)\. Note that the list below contains the options for both CPU\-only and CPU\-GPU versions of f5c\. Options related to the GPU (CUDA) do NOT apply to the CPU\-only version\.
.
.P
basic options:
.
.IP "\(bu" 4
\fB\-r FILE\fR:
.
.br
The file containing the base\-called reads in FASTQ or FASTA format\. Can be gzip compressed files\.
.
.IP "\(bu" 4
\fB\-b FILE\fR:
.
.br
The file contaning the alignment records sorted based on genomic coordinates in BAM format\.
.
.IP "\(bu" 4
\fB\-g FILE\fR:
.
.br
The file containing the reference genome in FASTA format\.
.
.IP "\(bu" 4
\fB\-w STR\fR:
.
.br
Only process the specified genomic region STR\. STR should be in the format \fIchr:start\-end\fR\. Currently, multiple region strings are not supported\. If this option is not specified, the whole genome will be processed\.
.
.IP "\(bu" 4
\fB\-t INT\fR:
.
.br
Number of processing threads [default value: 8]\. Ideally, this should be the number of CPU cores\.
.
.IP "\(bu" 4
\fB\-K INT\fR:
.
.br
Maximum number of reads loaded at once to the memory [default value: 512]\. A larger value maximises multithreading performance at cost of increased peak RAM\.
.
.IP "\(bu" 4
\fB\-B FLOAT[K/M/G]\fR:
.
.br
Maximum number of bases loaded at once to the memory [default value: 2\.0M]\. A larger value maximises multithreading performance at cost of increased peak RAM\.
.
.IP "\(bu" 4
\fB\-h\fR:
.
.br
Print the help to the standard out\.
.
.IP "\(bu" 4
\fB\-o FILE\fR:
.
.br
The file to write the output\. If this option is not specified, the output will be written to the standard out\.
.
.IP "\(bu" 4
\fB\-x STR\fR:
.
.br
Parameter profile to be used for maximising the performance to a particular computer system\. The profile parameters are always applied before other options, i\.e\., the user can override these parameters explicitly\. Some example profiles are laptop, desktop, hpc\. See profiles \fIhttps://f5c\.page\.link/profiles\fR for the full list and details\.
.
.IP "\(bu" 4
\fB\-\-iop INT\fR:
.
.br
Number of I/O processes to read FAST5 files [default value: 1]\. Increase this value if reading FAST5 limits the overall performance\. A higher value (can be as high as 64) is always preferred for systems with multiple disks (RAID) and network file systems\.
.
.IP "\(bu" 4
\fB\-\-slow5 FILE\fR:
.
.br
read raw signals from a slow5 file instead of fast5 files\. \-\-iop option is not required for slow5\.
.
.IP "\(bu" 4
\fB\-\-min\-mapq INT\fR:
.
.br
Minimum mapping quality of an alignment (MAPQ in the BAM record) to be considered for methylation calling [default value: 20]\.
.
.IP "\(bu" 4
\fB\-\-secondary=yes|no\fR:
.
.br
Whether secondary alignments are considered or not for methylation calling [default value: no]\.
.
.IP "\(bu" 4
\fB\-\-verbose INT\fR:
.
.br
Verbosity level for the log messages [default value: 0]\.
.
.IP "\(bu" 4
\fB\-\-version\fR:
.
.br
Print the version number to the standard out\.
.
.IP "\(bu" 4
\fB\-\-disable\-cuda=yes|no\fR:
.
.br
Disable running on the GPU or not [default value: no]\. If this option is set to yes, GPU acceleration is disabled\.
.
.IP "\(bu" 4
\fB\-\-cuda\-dev\-id INT\fR:
.
.br
CUDA device identifier to run GPU kernels on [default value: 0]\. The device identifier of the first GPU is 0, the second GPU is 1 and so on\. This can be found by invoking the \fBnvidia\-smi\fR command\. Currently, only a single GPU can be specified\. To utilise multiple GPUs, you have to manually invoke multiple f5c commands on different datasets with a different device identifier\.
.
.IP "\(bu" 4
\fB\-\-cuda\-max\-lf FLOAT\fR:
.
.br
Process reads with read\-length less than or equal to the product of \fIcuda\-max\-lf\fR and the average read length in the current batch on GPU\. The rest is processed on CPU [default value: 3\.0]\. Useful for tuning the CPU\-GPU load balance for atypical datasets\. Refer to performance guidelines \fIhttps://hasindu2008\.github\.io/f5c/docs/f5c\-perf\-hints\fR for details\.
.
.IP "\(bu" 4
\fB\-\-cuda\-avg\-epk FLOAT\fR:
.
.br
The average number of events\-per\-kmer used for allocating the arrays in GPU memory [default value: 2\.0]\. Useful for tuning the CPU\-GPU load balance for atypical datasets\. Refer to performance guidelines \fIhttps://hasindu2008\.github\.io/f5c/docs/f5c\-perf\-hints\fR for details\.
.
.IP "\(bu" 4
\fB\-\-cuda\-max\-epk FLOAT\fR:
.
.br
Process the reads with events\-per\-kmer less than or equal to \fIcuda_max_epk\fR on GPU\. The rest is processed on CPU [default value: 5\.0]\. Useful for tuning the CPU\-GPU load balance for atypical datasets\. Refer to performance guidelines \fIhttps://hasindu2008\.github\.io/f5c/docs/f5c\-perf\-hints\fR for details\.
.
.IP "" 0
.
.P
advanced options:
.
.IP "\(bu" 4
\fB\-\-skip\-ultra FILE\fR:
.
.br
Skip ultra\-long reads and write those alignment entries to the bam file provided as the argument\. Ultra\-long reads refer to reads longer than 100 kbases by default, unless specified by \-\-ultra\-thresh option below\. Useful for tuning the CPU\-GPU load balance for datasets containing many ultra\-long reads\. Also useful to cap the peak RAM usage in systems with limited memory\. After the execution, ultra\-long reads cab be separately processed, i\.e\., f5c can be again invoked on the produced bam file as the input\. Refer to performance guidelines \fIhttps://hasindu2008\.github\.io/f5c/docs/f5c\-perf\-hints\fR for details\.
.
.IP "\(bu" 4
\fB\-\-ultra\-thresh INT\fR:
.
.br
Threshold to skip ultra\-long reads [default value: 100000]\. This option is to be used in conjunction with \fB\-\-skip\-ultra\fR above\.
.
.IP "\(bu" 4
\fB\-\-skip\-unreadable=yes|no\fR:
.
.br
Whether to skip any unreadable fast5 files or to terminate the program [default value: yes]\. If \fByes\fR, the programme will continue to run while skipping unreadable fast5 files\. If \fBno\fR, the programme will terminate with an error when an unreadable fast5 file is found\.
.
.IP "\(bu" 4
\fB\-\-kmer\-model FILE\fR:
.
.br
Custom nucleotide k\-mer model file\. The file should adhere to the format in r9\.4_450bps\.nucleotide\.6mer\.template\.model \fIhttps://github\.com/hasindu2008/f5c/blob/master/test/r9\-models/r9\.4_450bps\.nucleotide\.6mer\.template\.model\fR\. The maximum supported k\-mer size is 6\.
.
.IP "\(bu" 4
\fB\-\-meth\-model FILE\fR:
.
.br
custom methylation k\-mer model file\. The file should adhere to the format in r9\.4_450bps\.cpg\.6mer\.template\.model \fIhttps://github\.com/hasindu2008/f5c/blob/master/test/r9\-models/r9\.4_450bps\.cpg\.6mer\.template\.model\fR\. The maximum supported k\-mer size is 6\.
.
.IP "\(bu" 4
\fB\-\-meth\-out\-version INT\fR:
.
.br
Format version of the output Methylation tsv file\. If set to 1, the columns printed adhere to the output format of Nanopolish early versions\. If set to 2, adhere to the latest nanopolish output format that additionally includes the strand column and the header num_cpgs renamed to \fInum_motifs\fR) [default value: 1]
.
.IP "\(bu" 4
\fB\-\-cuda\-mem\-frac FLOAT\fR:
.
.br
Fraction of free GPU memory to allocate [default value: 0\.9 for non\-tegra GPUs and 0\.7 for tegra GPUs]\. On GPUs with dedicated RAM (e\.g\., GeForce, Tesla and Quadro) almost all available free GPU memory can be allocated\. A slightly lower value such as 0\.9 is preferred instead of 1\.0 to prevent unexpected crashes\. In GPUs with integrated memory shared with RAM (e\.g\., Tegra GPUs that are in Jetson boards), this value should be at most 0\.7 to allow enough free RAM for both f5c and other programmes\.
.
.IP "" 0
.
.P
developer options:
.
.IP "\(bu" 4
\fB\-\-print\-events=yes|no\fR:
.
.br
Print the event table (the output of the event detection step) to the standard out\.
.
.IP "\(bu" 4
\fB\-\-print\-banded\-aln=yes|no\fR:
.
.br
Print the event alignment (the output of the adaptive banded event alignment step) to the standard out\.
.
.IP "\(bu" 4
\fB\-\-print\-scaling=yes|no\fR:
.
.br
Prints the estimated scaling values to the standard out\.
.
.IP "\(bu" 4
\fB\-\-print\-raw=yes|no\fR:
.
.br
Prints the raw signal to the standard out\.
.
.IP "\(bu" 4
\fB\-\-debug\-break INT\fR:
.
.br
Terminate the programme after processing the specified batch number\. E\.g\., If 0 is specified, the programme breaks after processing the 0th batch\.
.
.IP "\(bu" 4
\fB\-\-profile\-cpu=yes|no\fR:
.
.br
Process section by section and separately print the time spent on different steps such as the event detection, ABEA and HMM\. This option is used for profiling the workloads on the CPU\.
.
.IP "\(bu" 4
\fB\-\-write\-dump=yes|no\fR:
.
.br
Write the fast5 dump to a file or not\. The file name is hardcoded to f5c\.tmp\.bin and will be written to the current working directory\. The required raw signal data in the fast5 files subsequent processing will be serially written to \fIf5c\.tmp\.bin\fR\.
.
.IP "\(bu" 4
\fB\-\-read\-dump=yes|no\fR:
.
.br
Read from a fast5 dump file or not\. This is used to read from a dump file generated using \fB\-\-write\-dump\fR above\. The raw signal data will be serially loaded from the dump file instead of the fast5 files\.
.
.IP "" 0
.
.SS "meth\-freq"
\fBmeth\-freq [OPTIONS] \-i methcalls\.tsv\fR
.
.P
Calculate methylation frequency at genomic CpG sites from a tsv file containing methylation calls produced by f5c call\-methylation\. This is an optimised version of the nanopolish \fIcalculate_methylation_frequency\.py\fR script\.
.
.IP "\(bu" 4
\fB\-c FLOAT\fR:
.
.br
Call threshold for the log likelihood ratio [default value: 2\.5]\. If \fIabs(log_lik_ratio) < c\fR, those sites are considered ambigious and ignored when computing \fIcalled_sites\fR and \fIcalled_sites_methylated\fR\. If \fIlog_lik_ratio >= c\fR, those are considered methylated (\fIcalled_sites_methylated\fR)\.
.
.IP "\(bu" 4
\fB\-i FILE\fR:
.
.br
Input file containing methylation calls in tsv format (output of f5c call\-methylation)\. Read from stdin if not specified\. Any tsv file produced by f5c call\-methylation despite what was specified for \fB\-\-meth\-out\-version\fR (with/without strand column and/or num_cpg/num_motif) is supported and the format is automatically detected\.
.
.IP "\(bu" 4
\fB\-o FILE\fR:
.
.br
Output file to write the methylation frequencies in tsv format\. Write to stdout if not specified\.
.
.IP "\(bu" 4
\fB\-s\fR:
.
.br
Split groups\. If not specified, the default behaviour is to compute the methylation frequency per each group (a group contains nearby CpG sites considered together when calling methylation)\. If methylation frequency is required at an individual base resolution, this option must be specified to split the groups\.
.
.IP "\(bu" 4
\fB\-h\fR:
.
.br
Print the help to the standard out\.
.
.IP "\(bu" 4
\fB\-\-version\fR:
.
.br
Print the version number to the standard out\.
.
.IP "" 0
.
.SS "freq\-merge"
\fBf5c freq\-merge [OPTIONS] input1\.tsv input2\.tsv \.\.\.\fR
.
.P
Merge multiple methylation frequency tsv files (output files from f5c meth\-freq) to a single tsv file\. Useful to combine the results when meth\-freq was run separately on batches of reads, for instance, when performing real\-time methylation calling or an SGE array job\. Can be also used to merge methylation frequency tsv files from different samples as long as the reference genome used was the same\.
.
.P
For each methylation calling output (\.tsv) file, perform meth\-freq separately (without concatenation the input tsv files manually)\. Then feed those output (\.tsv) files to this tool, to obtain the final methylation frequency file\.
.
.IP "\(bu" 4
\fB\-o FILE\fR:
.
.br
Output file to write the methylation frequencies in tsv format\. Write to stdout if not specified\.
.
.IP "\(bu" 4
\fB\-h\fR:
.
.br
Print the help to the standard out\.
.
.IP "\(bu" 4
\fB\-\-version\fR:
.
.br
Print the version number to the standard out\.
.
.IP "" 0
.
.SS "eventalign"
.
.nf

f5c eventalign [OPTIONS] \-r reads\.fa \-b alignments\.bam \-g genome\.fa
f5c eventalign [OPTIONS] \-r reads\.fa \-b alignments\.bam \-g genome\.fa \-\-slow5 signals\.blow
.
.fi
.
.P
Align nanopore events to reference k\-mers (optimised nanopolish eventalign)\. Note that the list below contains the options for both CPU\-only and CPU\-GPU versions of f5c\. Options related to the GPU (CUDA) do NOT apply to the CPU\-only version\. As most
.
.P
basic options:
.
.IP "" 4
.
.nf

Same as those for call\-methylation and thus not repeated here\.
.
.fi
.
.IP "" 0
.
.P
advanced options:
.
.IP "\(bu" 4
\fB\-\-skip\-ultra FILE\fR:
.
.br
Same as for call\-methylation\.
.
.IP "\(bu" 4
\fB\-\-ultra\-thresh INT\fR:
.
.br
Same as for call\-methylation\.
.
.IP "\(bu" 4
\fB\-\-skip\-unreadable=yes|no\fR:
.
.br
Same as for call\-methylation\.
.
.IP "\(bu" 4
\fB\-\-kmer\-model FILE\fR:
.
.br
Same as for call\-methylation\.
.
.IP "\(bu" 4
\fB\-\-summary FILE\fR:
.
.br
Write the summaries of the alignment of each read to the file specified\.
.
.IP "\(bu" 4
\fB\-\-sam\fR:
.
.br
Write the alignment output in SAM format instead of tsv\.
.
.IP "\(bu" 4
\fB\-\-print\-read\-names\fR:
.
.br
Print read IDs instead of indexes\.
.
.IP "\(bu" 4
\fB\-\-scale\-events\fR:
.
.br
Scale events to the model, rather than vice\-versa\.
.
.IP "\(bu" 4
\fB\-\-samples\fR:
.
.br
Write the raw samples for the event to the tsv output\.
.
.IP "\(bu" 4
\fB\-\-rna\fR:
.
.br
Specify that this dataset is direct RNA\.
.
.IP "\(bu" 4
\fB\-\-signal\-index\fR:
.
.br
Write the raw signal start and end index values for the event to the tsv output\.
.
.IP "\(bu" 4
\fB\-\-cuda\-mem\-frac FLOAT\fR:
.
.br
Same as for call\-methylation\.
.
.IP "" 0
.
.P
developer options:
.
.IP "" 4
.
.nf

Same as those for call\-methylation and thus not repeated here\.
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
.
.TP
download and extract the dataset including sorted alignments
\fBwget \-O f5c_na12878_test\.tgz "https://f5c\.page\.link/f5c_na12878_test" tar xf f5c_na12878_test\.tgz\fR
.
.TP
index, call methylation and get methylation frequencies
\fBf5c index \-d chr22_meth_example/fast5_files chr22_meth_example/reads\.fastq f5c call\-methylation \-b chr22_meth_example/reads\.sorted\.bam \-g chr22_meth_example/humangenome\.fa \-r chr22_meth_example/reads\.fastq > chr22_meth_example/result\.tsv f5c meth\-freq \-i chr22_meth_example/result\.tsv > chr22_meth_example/freq\.tsv\fR
.
.TP
event alignment
\fBf5c eventalign \-b chr22_meth_example/reads\.sorted\.bam \-g chr22_meth_example/humangenome\.fa \-r chr22_meth_example/reads\.fastq > chr22_meth_example/events\.tsv\fR
.
.SH "AUTHOR"
Hasindu Gamaarachchi wrote the framework of f5c, CUDA code and integrated with adapted components from Jared T\. Simpson\'s Nanopolish \fIhttps://github\.com/jts/nanopolish\fR, with tremendous support from Chun Wai Lam, Gihan Jayatilaka and Hiruna Samarakoon\.
.
.SH "LICENSE"
f5c is licensed under the MIT License\. f5c reuses code and methods from Nanopolish \fIhttps://github\.com/jts/nanopolish\fR which is also under the MIT License\. The event detection code in f5c is from Oxford Nanopore\'s Scrappie basecaller \fIhttps://github\.com/nanoporetech/scrappie\fR which is under Mozilla Public License 2\.0\. Some code snippets have been taken from Minimap2 \fIhttps://github\.com/lh3/minimap2\fR and Samtools \fIhttps://github\.com/samtools/samtools\fR that are under the MIT License\.
.
.P
If you use f5c, please cite Gamaarachchi, H\., Lam, C\.W\., Jayatilaka, G\. et al\. GPU accelerated adaptive banded event alignment for rapid comparative nanopore signal analysis\. BMC Bioinformatics 21, 343 (2020)\. https://doi\.org/10\.1186/s12859\-020\-03697\-x
.
.SH "SEE ALSO"
Full documentation: https://hasindu2008\.github\.io/f5c/docs/overview
.
.P
Source code: https://github\.com/hasindu2008/f5c/
.
.P
Publication: https://bmcbioinformatics\.biomedcentral\.com/articles/10\.1186/s12859\-020\-03697\-x
